Migrate to aev3
akashic-contents/williamGorilla pull request #3
Opened 2022-04-06 10:26 UTC by ShinobuTakahashi

## 概要

AEv1 から AEv3 への移行に伴う修正

2022-04-06 10:29 UTC, ShinobuTakahashi commented on src/util/asaEx.ts
> +		static addAsaAssetIds(_pjNames: string[], _assetIds: string[]): void {
src/util/ 配下の関数の引数 `_assets` や `opt_assets` は利用側で引数を渡してないか `scene.assets` を渡していて `g.game.scene().assets` と同様のため削除し、`g.game.scene().asset.getXxxxxById()` 等を利用するよう修正。

2022-04-06 10:30 UTC, ShinobuTakahashi commented on src/classes/arrow.ts
> +	handleTap(_kind: number): number {
トリガーではない `onXxxxx()` の関数をコンテンツ内では `handleXxxxx()` へ名前を統一しています。

2022-04-07 06:45 UTC, yu-ogi requested changes
akashic-engine の import は避けたいです。

2022-04-07 06:45 UTC, yu-ogi commented on src/classes/timerLabel.ts
> +import { BitmapFont } from "@akashic/akashic-engine";
こちら削除してグローバルの `g` から参照したいです。

2022-04-07 06:45 UTC, yu-ogi commented on src/util/entityUtil.ts
> +import { BitmapFont } from "@akashic/akashic-engine";
こちらも同様です。

2022-04-07 07:21 UTC, ShinobuTakahashi commented on src/classes/timerLabel.ts
> +import { BitmapFont } from "@akashic/akashic-engine";
ありがとうございます。`g` から参照するうよう修正しました。

2022-04-07 07:21 UTC, ShinobuTakahashi commented on src/util/entityUtil.ts
> +import { BitmapFont } from "@akashic/akashic-engine";
修正しました。

2022-04-07 07:26 UTC, yu-ogi approved these changes

2022-04-07 10:19 UTC, kamakiri01 commented on src/common/mainSceneController.ts
> +	 * handleUpdateを呼ぶScene#updateのハンドラをこの中で登録する
nits
コメントアウト内も全体的にv3向けリプレイスの修正をされているので、 `Scene#update` は `Scene#onUpdate` に置き換えても良さそうです。

2022-04-07 10:19 UTC, kamakiri01 approved these changes

2022-04-07 10:56 UTC, ShinobuTakahashi commented on src/common/mainSceneController.ts
> +	 * handleUpdateを呼ぶScene#updateのハンドラをこの中で登録する
ありがとうございます。コメント内で漏れていた箇所を修正しました。

2022-04-08 03:24 UTC, merged